<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BASTET" failures="2" tests="4" name="First Register" time="39.726" errors="0" timestamp="2025-05-09T18:59:34 EEST">
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.738">
    <failure type="java.lang.AssertionError" message="Login failed or success message not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login failed or success message not found expected [true] but found [false]
at tests.LoginTest.testValidLogin(LoginTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="tests.LoginTest" name="testInvalidLogin" time="1.093"/>
  <testcase classname="tests.LoginTest" name="testBlankCredentials" time="0.641"/>
  <testcase classname="tests.LoginTest" name="testErrorMessageContent" time="0.801">
    <failure type="java.lang.AssertionError" message="Error message text not as expected. Actual: The username and password could not be verified. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message text not as expected. Actual: The username and password could not be verified. expected [true] but found [false]
at tests.LoginTest.testErrorMessageContent(LoginTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testErrorMessageContent -->
</testsuite> <!-- First Register -->
