<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BASTET" failures="1" tests="6" name="Open Account" time="65.401" errors="0" timestamp="2025-05-10T10:19:10 EEST">
  <testcase classname="tests.OpenAccountTest" name="TC12_navigateToOpenAccountPage" time="0.528"/>
  <testcase classname="tests.OpenAccountTest" name="TC13_openNewSavingsAccount" time="1.222"/>
  <testcase classname="tests.OpenAccountTest" name="TC14_verifyNewAccountCreated" time="0.738"/>
  <testcase classname="tests.OpenAccountTest" name="TC15_navigateToTransferFundsPage" time="0.66"/>
  <testcase classname="tests.OpenAccountTest" name="TC16_transferFundsBetweenAccounts" time="1.834"/>
  <testcase classname="tests.OpenAccountTest" name="TC17_attemptInvalidTransfer" time="5.989">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.OpenAccountTest.TC17_attemptInvalidTransfer(OpenAccountTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC17_attemptInvalidTransfer -->
</testsuite> <!-- Open Account -->
